# Generated by Django 6.0.7 on 2026-07-19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_seed_document_types"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="name",
        ),
        migrations.AlterField(
            model_name="document",
            name="document_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documents",
                to="core.documenttype",
            ),
        ),
    ]
