# Generated by Django 6.0.7 on 2026-07-19 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_milestone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workstream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(default='blue', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workstreams', to='core.project')),
            ],
            options={
                'ordering': ['display_order', 'name'],
                'unique_together': {('project', 'slug')},
            },
        ),
    ]
