# Generated by Django 6.0.7 on 2026-07-19 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_workstream'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='workstream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='core.workstream'),
        ),
    ]
